version: '3.1'
services:
  geopandas:
    build: .
    image: gsv2020-geopandas-buffer:latest
    environment:
      - INPUT_BUFFER_RADIUS_METERS=2000
      - INPUT_INPUT=/in.geojson
      - OUTPUT_BUFFERED_OUTPUT=/out.geojson
    volumes:
      - ./n52.geojson:/in.geojson